/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables;


import java.util.Collection;

import jhi.fab.codegen.Fab;
import jhi.fab.codegen.Keys;
import jhi.fab.codegen.tables.Outbreaks.OutbreaksPath;
import jhi.fab.codegen.tables.records.VarietiesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Varieties extends TableImpl<VarietiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fab.varieties</code>
     */
    public static final Varieties VARIETIES = new Varieties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VarietiesRecord> getRecordType() {
        return VarietiesRecord.class;
    }

    /**
     * The column <code>fab.varieties.variety_id</code>.
     */
    public final TableField<VarietiesRecord, Integer> VARIETY_ID = createField(DSL.name("variety_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>fab.varieties.variety_name</code>.
     */
    public final TableField<VarietiesRecord, String> VARIETY_NAME = createField(DSL.name("variety_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Varieties(Name alias, Table<VarietiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Varieties(Name alias, Table<VarietiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>fab.varieties</code> table reference
     */
    public Varieties(String alias) {
        this(DSL.name(alias), VARIETIES);
    }

    /**
     * Create an aliased <code>fab.varieties</code> table reference
     */
    public Varieties(Name alias) {
        this(alias, VARIETIES);
    }

    /**
     * Create a <code>fab.varieties</code> table reference
     */
    public Varieties() {
        this(DSL.name("varieties"), null);
    }

    public <O extends Record> Varieties(Table<O> path, ForeignKey<O, VarietiesRecord> childPath, InverseForeignKey<O, VarietiesRecord> parentPath) {
        super(path, childPath, parentPath, VARIETIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VarietiesPath extends Varieties implements Path<VarietiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VarietiesPath(Table<O> path, ForeignKey<O, VarietiesRecord> childPath, InverseForeignKey<O, VarietiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VarietiesPath(Name alias, Table<VarietiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VarietiesPath as(String alias) {
            return new VarietiesPath(DSL.name(alias), this);
        }

        @Override
        public VarietiesPath as(Name alias) {
            return new VarietiesPath(alias, this);
        }

        @Override
        public VarietiesPath as(Table<?> alias) {
            return new VarietiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Fab.FAB;
    }

    @Override
    public Identity<VarietiesRecord, Integer> getIdentity() {
        return (Identity<VarietiesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<VarietiesRecord> getPrimaryKey() {
        return Keys.KEY_VARIETIES_PRIMARY;
    }

    private transient OutbreaksPath _outbreaks;

    /**
     * Get the implicit to-many join path to the <code>fab.outbreaks</code>
     * table
     */
    public OutbreaksPath outbreaks() {
        if (_outbreaks == null)
            _outbreaks = new OutbreaksPath(this, null, Keys.OUTBREAKS_IBFK_1.getInverseKey());

        return _outbreaks;
    }

    @Override
    public Varieties as(String alias) {
        return new Varieties(DSL.name(alias), this);
    }

    @Override
    public Varieties as(Name alias) {
        return new Varieties(alias, this);
    }

    @Override
    public Varieties as(Table<?> alias) {
        return new Varieties(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Varieties rename(String name) {
        return new Varieties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Varieties rename(Name name) {
        return new Varieties(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Varieties rename(Table<?> name) {
        return new Varieties(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties where(Condition condition) {
        return new Varieties(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Varieties where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Varieties where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Varieties where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Varieties where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Varieties whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
