/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum OutbreaksHost implements EnumType {

    potato("potato"),

    tomato("tomato"),

    other("other");

    private final String literal;

    private OutbreaksHost(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static OutbreaksHost lookupLiteral(String literal) {
        return EnumType.lookupLiteral(OutbreaksHost.class, literal);
    }
}
