/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./components/BackButton.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    OutbreakDetails: typeof import('./components/OutbreakDetails.vue')['default']
    OutbreakMap: typeof import('./components/OutbreakMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sponsors: typeof import('./components/Sponsors.vue')['default']
  }
}
