/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen;


import jhi.fab.codegen.tables.Outbreaks;
import jhi.fab.codegen.tables.Subsamples;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fab.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SUBSAMPLES_GENOTYPE_ID = Internal.createIndex(DSL.name("genotype_id"), Subsamples.SUBSAMPLES, new OrderField[] { Subsamples.SUBSAMPLES.GENOTYPE_ID }, false);
    public static final Index SUBSAMPLES_OUTBREAK_ID = Internal.createIndex(DSL.name("outbreak_id"), Subsamples.SUBSAMPLES, new OrderField[] { Subsamples.SUBSAMPLES.OUTBREAK_ID }, false);
    public static final Index OUTBREAKS_SEVERITY_ID = Internal.createIndex(DSL.name("severity_id"), Outbreaks.OUTBREAKS, new OrderField[] { Outbreaks.OUTBREAKS.SEVERITY_ID }, false);
    public static final Index OUTBREAKS_SOURCE_ID = Internal.createIndex(DSL.name("source_id"), Outbreaks.OUTBREAKS, new OrderField[] { Outbreaks.OUTBREAKS.SOURCE_ID }, false);
    public static final Index OUTBREAKS_USER_ID = Internal.createIndex(DSL.name("user_id"), Outbreaks.OUTBREAKS, new OrderField[] { Outbreaks.OUTBREAKS.USER_ID }, false);
    public static final Index OUTBREAKS_VARIETY_ID = Internal.createIndex(DSL.name("variety_id"), Outbreaks.OUTBREAKS, new OrderField[] { Outbreaks.OUTBREAKS.VARIETY_ID }, false);
}
