/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen;


import jhi.fab.codegen.tables.Outbreaks;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in fab.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OUTBREAKS_OUTCODE = Internal.createIndex(DSL.name("outcode"), Outbreaks.OUTBREAKS, new OrderField[] { Outbreaks.OUTBREAKS.OUTCODE }, false);
}
