/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen;


import jhi.fab.codegen.tables.Outbreaks;
import jhi.fab.codegen.tables.Severities;
import jhi.fab.codegen.tables.Sources;
import jhi.fab.codegen.tables.SsrGenotypes;
import jhi.fab.codegen.tables.Subsamples;
import jhi.fab.codegen.tables.UserSessions;
import jhi.fab.codegen.tables.Users;
import jhi.fab.codegen.tables.Varieties;


/**
 * Convenience access to all tables in fab.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>fab.outbreaks</code>.
     */
    public static final Outbreaks OUTBREAKS = Outbreaks.OUTBREAKS;

    /**
     * The table <code>fab.severities</code>.
     */
    public static final Severities SEVERITIES = Severities.SEVERITIES;

    /**
     * The table <code>fab.sources</code>.
     */
    public static final Sources SOURCES = Sources.SOURCES;

    /**
     * The table <code>fab.ssr_genotypes</code>.
     */
    public static final SsrGenotypes SSR_GENOTYPES = SsrGenotypes.SSR_GENOTYPES;

    /**
     * The table <code>fab.subsamples</code>.
     */
    public static final Subsamples SUBSAMPLES = Subsamples.SUBSAMPLES;

    /**
     * The table <code>fab.user_sessions</code>.
     */
    public static final UserSessions USER_SESSIONS = UserSessions.USER_SESSIONS;

    /**
     * The table <code>fab.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>fab.varieties</code>.
     */
    public static final Varieties VARIETIES = Varieties.VARIETIES;
}
