/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import jhi.fab.codegen.tables.Nuts;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NutsRecord extends UpdatableRecordImpl<NutsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.nuts.nuts_id</code>.
     */
    public void setNutsId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.nuts.nuts_id</code>.
     */
    public Integer getNutsId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.nuts.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.nuts.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.nuts.country_id</code>.
     */
    public void setCountryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.nuts.country_id</code>.
     */
    public Integer getCountryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NutsRecord
     */
    public NutsRecord() {
        super(Nuts.NUTS);
    }

    /**
     * Create a detached, initialised NutsRecord
     */
    public NutsRecord(Integer nutsId, String name, Integer countryId) {
        super(Nuts.NUTS);

        setNutsId(nutsId);
        setName(name);
        setCountryId(countryId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised NutsRecord
     */
    public NutsRecord(jhi.fab.codegen.tables.pojos.Nuts value) {
        super(Nuts.NUTS);

        if (value != null) {
            setNutsId(value.getNutsId());
            setName(value.getName());
            setCountryId(value.getCountryId());
            resetTouchedOnNotNull();
        }
    }
}
