/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.enums.OutbreaksStatus;
import jhi.fab.codegen.tables.Outbreaks;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutbreaksRecord extends UpdatableRecordImpl<OutbreaksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public void setOutbreakCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public String getOutbreakCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.outbreaks.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fab.outbreaks.real_latitude</code>.
     */
    public void setRealLatitude(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.outbreaks.real_latitude</code>.
     */
    public Double getRealLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>fab.outbreaks.real_longitude</code>.
     */
    public void setRealLongitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.outbreaks.real_longitude</code>.
     */
    public Double getRealLongitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>fab.outbreaks.view_latitude</code>.
     */
    public void setViewLatitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.outbreaks.view_latitude</code>.
     */
    public Double getViewLatitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>fab.outbreaks.view_longitude</code>.
     */
    public void setViewLongitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.outbreaks.view_longitude</code>.
     */
    public Double getViewLongitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>fab.outbreaks.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.outbreaks.date_submitted</code>.
     */
    public LocalDate getDateSubmitted() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>fab.outbreaks.date_received</code>.
     */
    public void setDateReceived(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.outbreaks.date_received</code>.
     */
    public LocalDate getDateReceived() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>fab.outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>fab.outbreaks.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>fab.outbreaks.severity_other</code>.
     */
    public void setSeverityOther(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fab.outbreaks.severity_other</code>.
     */
    public String getSeverityOther() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fab.outbreaks.source_other</code>.
     */
    public void setSourceOther(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fab.outbreaks.source_other</code>.
     */
    public String getSourceOther() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fab.outbreaks.comments</code>.
     */
    public void setComments(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fab.outbreaks.comments</code>.
     */
    public String getComments() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fab.outbreaks.additional_info</code>.
     */
    public void setAdditionalInfo(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fab.outbreaks.additional_info</code>.
     */
    public String getAdditionalInfo() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fab.outbreaks.status</code>.
     */
    public void setStatus(OutbreaksStatus value) {
        set(15, value);
    }

    /**
     * Getter for <code>fab.outbreaks.status</code>.
     */
    public OutbreaksStatus getStatus() {
        return (OutbreaksStatus) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutbreaksRecord
     */
    public OutbreaksRecord() {
        super(Outbreaks.OUTBREAKS);
    }

    /**
     * Create a detached, initialised OutbreaksRecord
     */
    public OutbreaksRecord(Integer outbreakId, String outbreakCode, Integer userId, Double realLatitude, Double realLongitude, Double viewLatitude, Double viewLongitude, LocalDate dateSubmitted, LocalDate dateReceived, Integer severityId, Integer sourceId, String severityOther, String sourceOther, String comments, String additionalInfo, OutbreaksStatus status) {
        super(Outbreaks.OUTBREAKS);

        setOutbreakId(outbreakId);
        setOutbreakCode(outbreakCode);
        setUserId(userId);
        setRealLatitude(realLatitude);
        setRealLongitude(realLongitude);
        setViewLatitude(viewLatitude);
        setViewLongitude(viewLongitude);
        setDateSubmitted(dateSubmitted);
        setDateReceived(dateReceived);
        setSeverityId(severityId);
        setSourceId(sourceId);
        setSeverityOther(severityOther);
        setSourceOther(sourceOther);
        setComments(comments);
        setAdditionalInfo(additionalInfo);
        setStatus(status);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised OutbreaksRecord
     */
    public OutbreaksRecord(jhi.fab.codegen.tables.pojos.Outbreaks value) {
        super(Outbreaks.OUTBREAKS);

        if (value != null) {
            setOutbreakId(value.getOutbreakId());
            setOutbreakCode(value.getOutbreakCode());
            setUserId(value.getUserId());
            setRealLatitude(value.getRealLatitude());
            setRealLongitude(value.getRealLongitude());
            setViewLatitude(value.getViewLatitude());
            setViewLongitude(value.getViewLongitude());
            setDateSubmitted(value.getDateSubmitted());
            setDateReceived(value.getDateReceived());
            setSeverityId(value.getSeverityId());
            setSourceId(value.getSourceId());
            setSeverityOther(value.getSeverityOther());
            setSourceOther(value.getSourceOther());
            setComments(value.getComments());
            setAdditionalInfo(value.getAdditionalInfo());
            setStatus(value.getStatus());
            resetTouchedOnNotNull();
        }
    }
}
