/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jhi.fab.codegen.enums.OutbreaksStatus;
import jhi.fab.codegen.tables.Outbreaks;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutbreaksRecord extends UpdatableRecordImpl<OutbreaksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.outbreaks.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fab.outbreaks.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.outbreaks.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>fab.outbreaks.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.outbreaks.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>fab.outbreaks.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.outbreaks.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fab.outbreaks.variety_id</code>.
     */
    public void setVarietyId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.outbreaks.variety_id</code>.
     */
    public Integer getVarietyId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fab.outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fab.outbreaks.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>fab.outbreaks.severityOther</code>.
     */
    public void setSeverityother(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.outbreaks.severityOther</code>.
     */
    public String getSeverityother() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fab.outbreaks.sourceOther</code>.
     */
    public void setSourceother(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.outbreaks.sourceOther</code>.
     */
    public String getSourceother() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fab.outbreaks.comments</code>.
     */
    public void setComments(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.outbreaks.comments</code>.
     */
    public String getComments() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fab.outbreaks.additionalInfo</code>.
     */
    public void setAdditionalinfo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fab.outbreaks.additionalInfo</code>.
     */
    public String getAdditionalinfo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fab.outbreaks.status</code>.
     */
    public void setStatus(OutbreaksStatus value) {
        set(12, value);
    }

    /**
     * Getter for <code>fab.outbreaks.status</code>.
     */
    public OutbreaksStatus getStatus() {
        return (OutbreaksStatus) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutbreaksRecord
     */
    public OutbreaksRecord() {
        super(Outbreaks.OUTBREAKS);
    }

    /**
     * Create a detached, initialised OutbreaksRecord
     */
    public OutbreaksRecord(Integer outbreakId, Integer userId, BigDecimal latitude, BigDecimal longitude, LocalDateTime date, Integer varietyId, Integer severityId, Integer sourceId, String severityother, String sourceother, String comments, String additionalinfo, OutbreaksStatus status) {
        super(Outbreaks.OUTBREAKS);

        setOutbreakId(outbreakId);
        setUserId(userId);
        setLatitude(latitude);
        setLongitude(longitude);
        setDate(date);
        setVarietyId(varietyId);
        setSeverityId(severityId);
        setSourceId(sourceId);
        setSeverityother(severityother);
        setSourceother(sourceother);
        setComments(comments);
        setAdditionalinfo(additionalinfo);
        setStatus(status);
        resetTouchedOnNotNull();
    }
}
