/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import jhi.fab.codegen.tables.Severities;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SeveritiesRecord extends UpdatableRecordImpl<SeveritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.severities.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.severities.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.severities.severity_name</code>.
     */
    public void setSeverityName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.severities.severity_name</code>.
     */
    public String getSeverityName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeveritiesRecord
     */
    public SeveritiesRecord() {
        super(Severities.SEVERITIES);
    }

    /**
     * Create a detached, initialised SeveritiesRecord
     */
    public SeveritiesRecord(Integer severityId, String severityName) {
        super(Severities.SEVERITIES);

        setSeverityId(severityId);
        setSeverityName(severityName);
        resetTouchedOnNotNull();
    }
}
