/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import jhi.fab.codegen.tables.Sources;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SourcesRecord extends UpdatableRecordImpl<SourcesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.sources.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.sources.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.sources.source_name</code>.
     */
    public void setSourceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.sources.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourcesRecord
     */
    public SourcesRecord() {
        super(Sources.SOURCES);
    }

    /**
     * Create a detached, initialised SourcesRecord
     */
    public SourcesRecord(Integer sourceId, String sourceName) {
        super(Sources.SOURCES);

        setSourceId(sourceId);
        setSourceName(sourceName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SourcesRecord
     */
    public SourcesRecord(jhi.fab.codegen.tables.pojos.Sources value) {
        super(Sources.SOURCES);

        if (value != null) {
            setSourceId(value.getSourceId());
            setSourceName(value.getSourceName());
            resetTouchedOnNotNull();
        }
    }
}
