/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.tables.Subsamples;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubsamplesRecord extends UpdatableRecordImpl<SubsamplesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.subsamples.subsample_id</code>.
     */
    public void setSubsampleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.subsamples.subsample_id</code>.
     */
    public Integer getSubsampleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.subsamples.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.subsamples.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fab.subsamples.genotype_id</code>.
     */
    public void setGenotypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.subsamples.genotype_id</code>.
     */
    public Integer getGenotypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fab.subsamples.dateGenotyped</code>.
     */
    public void setDategenotyped(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.subsamples.dateGenotyped</code>.
     */
    public LocalDate getDategenotyped() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>fab.subsamples.comments</code>.
     */
    public void setComments(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.subsamples.comments</code>.
     */
    public String getComments() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubsamplesRecord
     */
    public SubsamplesRecord() {
        super(Subsamples.SUBSAMPLES);
    }

    /**
     * Create a detached, initialised SubsamplesRecord
     */
    public SubsamplesRecord(Integer subsampleId, Integer outbreakId, Integer genotypeId, LocalDate dategenotyped, String comments) {
        super(Subsamples.SUBSAMPLES);

        setSubsampleId(subsampleId);
        setOutbreakId(outbreakId);
        setGenotypeId(genotypeId);
        setDategenotyped(dategenotyped);
        setComments(comments);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SubsamplesRecord
     */
    public SubsamplesRecord(jhi.fab.codegen.tables.pojos.Subsamples value) {
        super(Subsamples.SUBSAMPLES);

        if (value != null) {
            setSubsampleId(value.getSubsampleId());
            setOutbreakId(value.getOutbreakId());
            setGenotypeId(value.getGenotypeId());
            setDategenotyped(value.getDategenotyped());
            setComments(value.getComments());
            resetTouchedOnNotNull();
        }
    }
}
