/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.enums.SubsamplesMatingType;
import jhi.fab.codegen.tables.Subsamples;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubsamplesRecord extends UpdatableRecordImpl<SubsamplesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.subsamples.subsample_id</code>.
     */
    public void setSubsampleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.subsamples.subsample_id</code>.
     */
    public Integer getSubsampleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.subsamples.subsample_code</code>.
     */
    public void setSubsampleCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.subsamples.subsample_code</code>.
     */
    public String getSubsampleCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.subsamples.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.subsamples.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fab.subsamples.genotype_id</code>.
     */
    public void setGenotypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.subsamples.genotype_id</code>.
     */
    public Integer getGenotypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fab.subsamples.variety_id</code>.
     */
    public void setVarietyId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.subsamples.variety_id</code>.
     */
    public Integer getVarietyId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>fab.subsamples.material</code>.
     */
    public void setMaterial(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.subsamples.material</code>.
     */
    public String getMaterial() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fab.subsamples.date_genotyped</code>.
     */
    public void setDateGenotyped(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.subsamples.date_genotyped</code>.
     */
    public LocalDate getDateGenotyped() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>fab.subsamples.admin_comments</code>.
     */
    public void setAdminComments(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.subsamples.admin_comments</code>.
     */
    public String getAdminComments() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fab.subsamples.mycelia_pellet</code>.
     */
    public void setMyceliaPellet(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.subsamples.mycelia_pellet</code>.
     */
    public Boolean getMyceliaPellet() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>fab.subsamples.culture_slope</code>.
     */
    public void setCultureSlope(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.subsamples.culture_slope</code>.
     */
    public Boolean getCultureSlope() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>fab.subsamples.mating_type</code>.
     */
    public void setMatingType(SubsamplesMatingType value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.subsamples.mating_type</code>.
     */
    public SubsamplesMatingType getMatingType() {
        return (SubsamplesMatingType) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubsamplesRecord
     */
    public SubsamplesRecord() {
        super(Subsamples.SUBSAMPLES);
    }

    /**
     * Create a detached, initialised SubsamplesRecord
     */
    public SubsamplesRecord(Integer subsampleId, String subsampleCode, Integer outbreakId, Integer genotypeId, Integer varietyId, String material, LocalDate dateGenotyped, String adminComments, Boolean myceliaPellet, Boolean cultureSlope, SubsamplesMatingType matingType) {
        super(Subsamples.SUBSAMPLES);

        setSubsampleId(subsampleId);
        setSubsampleCode(subsampleCode);
        setOutbreakId(outbreakId);
        setGenotypeId(genotypeId);
        setVarietyId(varietyId);
        setMaterial(material);
        setDateGenotyped(dateGenotyped);
        setAdminComments(adminComments);
        setMyceliaPellet(myceliaPellet);
        setCultureSlope(cultureSlope);
        setMatingType(matingType);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised SubsamplesRecord
     */
    public SubsamplesRecord(jhi.fab.codegen.tables.pojos.Subsamples value) {
        super(Subsamples.SUBSAMPLES);

        if (value != null) {
            setSubsampleId(value.getSubsampleId());
            setSubsampleCode(value.getSubsampleCode());
            setOutbreakId(value.getOutbreakId());
            setGenotypeId(value.getGenotypeId());
            setVarietyId(value.getVarietyId());
            setMaterial(value.getMaterial());
            setDateGenotyped(value.getDateGenotyped());
            setAdminComments(value.getAdminComments());
            setMyceliaPellet(value.getMyceliaPellet());
            setCultureSlope(value.getCultureSlope());
            setMatingType(value.getMatingType());
            resetTouchedOnNotNull();
        }
    }
}
