/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDateTime;

import jhi.fab.codegen.tables.UserSessions;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserSessionsRecord extends UpdatableRecordImpl<UserSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.user_sessions.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.user_sessions.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.user_sessions.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.user_sessions.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.user_sessions.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.user_sessions.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSessionsRecord
     */
    public UserSessionsRecord() {
        super(UserSessions.USER_SESSIONS);
    }

    /**
     * Create a detached, initialised UserSessionsRecord
     */
    public UserSessionsRecord(Integer userId, String token, LocalDateTime createdOn) {
        super(UserSessions.USER_SESSIONS);

        setUserId(userId);
        setToken(token);
        setCreatedOn(createdOn);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserSessionsRecord
     */
    public UserSessionsRecord(jhi.fab.codegen.tables.pojos.UserSessions value) {
        super(UserSessions.USER_SESSIONS);

        if (value != null) {
            setUserId(value.getUserId());
            setToken(value.getToken());
            setCreatedOn(value.getCreatedOn());
            resetTouchedOnNotNull();
        }
    }
}
