/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.enums.ViewOutbreaksHost;
import jhi.fab.codegen.enums.ViewOutbreaksStatus;
import jhi.fab.codegen.tables.ViewOutbreaks;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewOutbreaksRecord extends TableRecordImpl<ViewOutbreaksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.view_outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.view_outbreaks.outbreak_code</code>.
     */
    public void setOutbreakCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.outbreak_code</code>.
     */
    public String getOutbreakCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.view_outbreaks.postcode</code>.
     */
    public void setPostcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.postcode</code>.
     */
    public String getPostcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fab.view_outbreaks.outcode</code>.
     */
    public void setOutcode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.outcode</code>.
     */
    public String getOutcode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fab.view_outbreaks.country</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.country</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fab.view_outbreaks.itl_nuts</code>.
     */
    public void setItlNuts(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.itl_nuts</code>.
     */
    public String getItlNuts() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fab.view_outbreaks.date_received</code>.
     */
    public void setDateReceived(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.date_received</code>.
     */
    public LocalDate getDateReceived() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>fab.view_outbreaks.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.date_submitted</code>.
     */
    public LocalDate getDateSubmitted() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>fab.view_outbreaks.real_latitude</code>.
     */
    public void setRealLatitude(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.real_latitude</code>.
     */
    public Double getRealLatitude() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>fab.view_outbreaks.real_longitude</code>.
     */
    public void setRealLongitude(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.real_longitude</code>.
     */
    public Double getRealLongitude() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>fab.view_outbreaks.view_latitude</code>.
     */
    public void setViewLatitude(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.view_latitude</code>.
     */
    public Double getViewLatitude() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>fab.view_outbreaks.view_longitude</code>.
     */
    public void setViewLongitude(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.view_longitude</code>.
     */
    public Double getViewLongitude() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_comments</code>.
     */
    public void setUserComments(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_comments</code>.
     */
    public String getUserComments() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fab.view_outbreaks.admin_comments</code>.
     */
    public void setAdminComments(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.admin_comments</code>.
     */
    public String getAdminComments() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fab.view_outbreaks.status</code>.
     */
    public void setStatus(ViewOutbreaksStatus value) {
        set(14, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.status</code>.
     */
    public ViewOutbreaksStatus getStatus() {
        return (ViewOutbreaksStatus) get(14);
    }

    /**
     * Setter for <code>fab.view_outbreaks.host</code>.
     */
    public void setHost(ViewOutbreaksHost value) {
        set(15, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.host</code>.
     */
    public ViewOutbreaksHost getHost() {
        return (ViewOutbreaksHost) get(15);
    }

    /**
     * Setter for <code>fab.view_outbreaks.is_public</code>.
     */
    public void setIsPublic(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.is_public</code>.
     */
    public Boolean getIsPublic() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>fab.view_outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>fab.view_outbreaks.severity_name</code>.
     */
    public void setSeverityName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.severity_name</code>.
     */
    public String getSeverityName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>fab.view_outbreaks.severity_other</code>.
     */
    public void setSeverityOther(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.severity_other</code>.
     */
    public String getSeverityOther() {
        return (String) get(19);
    }

    /**
     * Setter for <code>fab.view_outbreaks.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>fab.view_outbreaks.source_name</code>.
     */
    public void setSourceName(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(21);
    }

    /**
     * Setter for <code>fab.view_outbreaks.source_other</code>.
     */
    public void setSourceOther(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.source_other</code>.
     */
    public String getSourceOther() {
        return (String) get(22);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>fab.view_outbreaks.is_admin</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_email</code>.
     */
    public void setUserEmail(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_email</code>.
     */
    public String getUserEmail() {
        return (String) get(25);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_name</code>.
     */
    public void setUserName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_name</code>.
     */
    public String getUserName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>fab.view_outbreaks.reported_variety_id</code>.
     */
    public void setReportedVarietyId(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.reported_variety_id</code>.
     */
    public Integer getReportedVarietyId() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>fab.view_outbreaks.reported_variety_name</code>.
     */
    public void setReportedVarietyName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.reported_variety_name</code>.
     */
    public String getReportedVarietyName() {
        return (String) get(28);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord() {
        super(ViewOutbreaks.VIEW_OUTBREAKS);
    }

    /**
     * Create a detached, initialised ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord(Integer outbreakId, String outbreakCode, String postcode, String outcode, String country, String itlNuts, LocalDate dateReceived, LocalDate dateSubmitted, Double realLatitude, Double realLongitude, Double viewLatitude, Double viewLongitude, String userComments, String adminComments, ViewOutbreaksStatus status, ViewOutbreaksHost host, Boolean isPublic, Integer severityId, String severityName, String severityOther, Integer sourceId, String sourceName, String sourceOther, Integer userId, Boolean isAdmin, String userEmail, String userName, Integer reportedVarietyId, String reportedVarietyName) {
        super(ViewOutbreaks.VIEW_OUTBREAKS);

        setOutbreakId(outbreakId);
        setOutbreakCode(outbreakCode);
        setPostcode(postcode);
        setOutcode(outcode);
        setCountry(country);
        setItlNuts(itlNuts);
        setDateReceived(dateReceived);
        setDateSubmitted(dateSubmitted);
        setRealLatitude(realLatitude);
        setRealLongitude(realLongitude);
        setViewLatitude(viewLatitude);
        setViewLongitude(viewLongitude);
        setUserComments(userComments);
        setAdminComments(adminComments);
        setStatus(status);
        setHost(host);
        setIsPublic(isPublic);
        setSeverityId(severityId);
        setSeverityName(severityName);
        setSeverityOther(severityOther);
        setSourceId(sourceId);
        setSourceName(sourceName);
        setSourceOther(sourceOther);
        setUserId(userId);
        setIsAdmin(isAdmin);
        setUserEmail(userEmail);
        setUserName(userName);
        setReportedVarietyId(reportedVarietyId);
        setReportedVarietyName(reportedVarietyName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord(jhi.fab.codegen.tables.pojos.ViewOutbreaks value) {
        super(ViewOutbreaks.VIEW_OUTBREAKS);

        if (value != null) {
            setOutbreakId(value.getOutbreakId());
            setOutbreakCode(value.getOutbreakCode());
            setPostcode(value.getPostcode());
            setOutcode(value.getOutcode());
            setCountry(value.getCountry());
            setItlNuts(value.getItlNuts());
            setDateReceived(value.getDateReceived());
            setDateSubmitted(value.getDateSubmitted());
            setRealLatitude(value.getRealLatitude());
            setRealLongitude(value.getRealLongitude());
            setViewLatitude(value.getViewLatitude());
            setViewLongitude(value.getViewLongitude());
            setUserComments(value.getUserComments());
            setAdminComments(value.getAdminComments());
            setStatus(value.getStatus());
            setHost(value.getHost());
            setIsPublic(value.getIsPublic());
            setSeverityId(value.getSeverityId());
            setSeverityName(value.getSeverityName());
            setSeverityOther(value.getSeverityOther());
            setSourceId(value.getSourceId());
            setSourceName(value.getSourceName());
            setSourceOther(value.getSourceOther());
            setUserId(value.getUserId());
            setIsAdmin(value.getIsAdmin());
            setUserEmail(value.getUserEmail());
            setUserName(value.getUserName());
            setReportedVarietyId(value.getReportedVarietyId());
            setReportedVarietyName(value.getReportedVarietyName());
            resetTouchedOnNotNull();
        }
    }
}
