/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.enums.ViewOutbreaksStatus;
import jhi.fab.codegen.tables.ViewOutbreaks;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewOutbreaksRecord extends TableRecordImpl<ViewOutbreaksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.view_outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.view_outbreaks.outbreak_code</code>.
     */
    public void setOutbreakCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.outbreak_code</code>.
     */
    public String getOutbreakCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.view_outbreaks.date_received</code>.
     */
    public void setDateReceived(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.date_received</code>.
     */
    public LocalDate getDateReceived() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>fab.view_outbreaks.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.date_submitted</code>.
     */
    public LocalDate getDateSubmitted() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>fab.view_outbreaks.real_latitude</code>.
     */
    public void setRealLatitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.real_latitude</code>.
     */
    public Double getRealLatitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>fab.view_outbreaks.real_longitude</code>.
     */
    public void setRealLongitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.real_longitude</code>.
     */
    public Double getRealLongitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>fab.view_outbreaks.view_latitude</code>.
     */
    public void setViewLatitude(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.view_latitude</code>.
     */
    public Double getViewLatitude() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>fab.view_outbreaks.view_longitude</code>.
     */
    public void setViewLongitude(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.view_longitude</code>.
     */
    public Double getViewLongitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>fab.view_outbreaks.status</code>.
     */
    public void setStatus(ViewOutbreaksStatus value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.status</code>.
     */
    public ViewOutbreaksStatus getStatus() {
        return (ViewOutbreaksStatus) get(8);
    }

    /**
     * Setter for <code>fab.view_outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>fab.view_outbreaks.severity_name</code>.
     */
    public void setSeverityName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.severity_name</code>.
     */
    public String getSeverityName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fab.view_outbreaks.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>fab.view_outbreaks.source_name</code>.
     */
    public void setSourceName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>fab.view_outbreaks.is_admin</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_email</code>.
     */
    public void setUserEmail(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_email</code>.
     */
    public String getUserEmail() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fab.view_outbreaks.user_name</code>.
     */
    public void setUserName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>fab.view_outbreaks.user_name</code>.
     */
    public String getUserName() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord() {
        super(ViewOutbreaks.VIEW_OUTBREAKS);
    }

    /**
     * Create a detached, initialised ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord(Integer outbreakId, String outbreakCode, LocalDate dateReceived, LocalDate dateSubmitted, Double realLatitude, Double realLongitude, Double viewLatitude, Double viewLongitude, ViewOutbreaksStatus status, Integer severityId, String severityName, Integer sourceId, String sourceName, Integer userId, Boolean isAdmin, String userEmail, String userName) {
        super(ViewOutbreaks.VIEW_OUTBREAKS);

        setOutbreakId(outbreakId);
        setOutbreakCode(outbreakCode);
        setDateReceived(dateReceived);
        setDateSubmitted(dateSubmitted);
        setRealLatitude(realLatitude);
        setRealLongitude(realLongitude);
        setViewLatitude(viewLatitude);
        setViewLongitude(viewLongitude);
        setStatus(status);
        setSeverityId(severityId);
        setSeverityName(severityName);
        setSourceId(sourceId);
        setSourceName(sourceName);
        setUserId(userId);
        setIsAdmin(isAdmin);
        setUserEmail(userEmail);
        setUserName(userName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewOutbreaksRecord
     */
    public ViewOutbreaksRecord(jhi.fab.codegen.tables.pojos.ViewOutbreaks value) {
        super(ViewOutbreaks.VIEW_OUTBREAKS);

        if (value != null) {
            setOutbreakId(value.getOutbreakId());
            setOutbreakCode(value.getOutbreakCode());
            setDateReceived(value.getDateReceived());
            setDateSubmitted(value.getDateSubmitted());
            setRealLatitude(value.getRealLatitude());
            setRealLongitude(value.getRealLongitude());
            setViewLatitude(value.getViewLatitude());
            setViewLongitude(value.getViewLongitude());
            setStatus(value.getStatus());
            setSeverityId(value.getSeverityId());
            setSeverityName(value.getSeverityName());
            setSourceId(value.getSourceId());
            setSourceName(value.getSourceName());
            setUserId(value.getUserId());
            setIsAdmin(value.getIsAdmin());
            setUserEmail(value.getUserEmail());
            setUserName(value.getUserName());
            resetTouchedOnNotNull();
        }
    }
}
