/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.records;


import java.time.LocalDate;

import jhi.fab.codegen.enums.ViewSubsamplesMatingType;
import jhi.fab.codegen.tables.ViewSubsamples;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewSubsamplesRecord extends TableRecordImpl<ViewSubsamplesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fab.view_subsamples.subsample_id</code>.
     */
    public void setSubsampleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.subsample_id</code>.
     */
    public Integer getSubsampleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fab.view_subsamples.subsample_code</code>.
     */
    public void setSubsampleCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.subsample_code</code>.
     */
    public String getSubsampleCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fab.view_subsamples.outbreak_id</code>.
     */
    public void setOutbreakId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fab.view_subsamples.genotype_id</code>.
     */
    public void setGenotypeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.genotype_id</code>.
     */
    public Integer getGenotypeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fab.view_subsamples.genotype_name</code>.
     */
    public void setGenotypeName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.genotype_name</code>.
     */
    public String getGenotypeName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fab.view_subsamples.material</code>.
     */
    public void setMaterial(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.material</code>.
     */
    public String getMaterial() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fab.view_subsamples.date_genotyped</code>.
     */
    public void setDateGenotyped(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.date_genotyped</code>.
     */
    public LocalDate getDateGenotyped() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>fab.view_subsamples.admin_comments</code>.
     */
    public void setAdminComments(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.admin_comments</code>.
     */
    public String getAdminComments() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fab.view_subsamples.variety_id</code>.
     */
    public void setVarietyId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.variety_id</code>.
     */
    public Integer getVarietyId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>fab.view_subsamples.variety_name</code>.
     */
    public void setVarietyName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.variety_name</code>.
     */
    public String getVarietyName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fab.view_subsamples.mycelia_pellet</code>.
     */
    public void setMyceliaPellet(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.mycelia_pellet</code>.
     */
    public Boolean getMyceliaPellet() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>fab.view_subsamples.culture_slope</code>.
     */
    public void setCultureSlope(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.culture_slope</code>.
     */
    public Boolean getCultureSlope() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>fab.view_subsamples.mating_type</code>.
     */
    public void setMatingType(ViewSubsamplesMatingType value) {
        set(12, value);
    }

    /**
     * Getter for <code>fab.view_subsamples.mating_type</code>.
     */
    public ViewSubsamplesMatingType getMatingType() {
        return (ViewSubsamplesMatingType) get(12);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewSubsamplesRecord
     */
    public ViewSubsamplesRecord() {
        super(ViewSubsamples.VIEW_SUBSAMPLES);
    }

    /**
     * Create a detached, initialised ViewSubsamplesRecord
     */
    public ViewSubsamplesRecord(Integer subsampleId, String subsampleCode, Integer outbreakId, Integer genotypeId, String genotypeName, String material, LocalDate dateGenotyped, String adminComments, Integer varietyId, String varietyName, Boolean myceliaPellet, Boolean cultureSlope, ViewSubsamplesMatingType matingType) {
        super(ViewSubsamples.VIEW_SUBSAMPLES);

        setSubsampleId(subsampleId);
        setSubsampleCode(subsampleCode);
        setOutbreakId(outbreakId);
        setGenotypeId(genotypeId);
        setGenotypeName(genotypeName);
        setMaterial(material);
        setDateGenotyped(dateGenotyped);
        setAdminComments(adminComments);
        setVarietyId(varietyId);
        setVarietyName(varietyName);
        setMyceliaPellet(myceliaPellet);
        setCultureSlope(cultureSlope);
        setMatingType(matingType);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewSubsamplesRecord
     */
    public ViewSubsamplesRecord(jhi.fab.codegen.tables.pojos.ViewSubsamples value) {
        super(ViewSubsamples.VIEW_SUBSAMPLES);

        if (value != null) {
            setSubsampleId(value.getSubsampleId());
            setSubsampleCode(value.getSubsampleCode());
            setOutbreakId(value.getOutbreakId());
            setGenotypeId(value.getGenotypeId());
            setGenotypeName(value.getGenotypeName());
            setMaterial(value.getMaterial());
            setDateGenotyped(value.getDateGenotyped());
            setAdminComments(value.getAdminComments());
            setVarietyId(value.getVarietyId());
            setVarietyName(value.getVarietyName());
            setMyceliaPellet(value.getMyceliaPellet());
            setCultureSlope(value.getCultureSlope());
            setMatingType(value.getMatingType());
            resetTouchedOnNotNull();
        }
    }
}
