/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Countries implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer countryId;
    private String name;

    public Countries() {}

    public Countries(Countries value) {
        this.countryId = value.countryId;
        this.name = value.name;
    }

    public Countries(
        Integer countryId,
        String name
    ) {
        this.countryId = countryId;
        this.name = name;
    }

    /**
     * Getter for <code>fab.countries.country_id</code>.
     */
    public Integer getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>fab.countries.country_id</code>.
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * Getter for <code>fab.countries.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>fab.countries.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Countries other = (Countries) obj;
        if (this.countryId == null) {
            if (other.countryId != null)
                return false;
        }
        else if (!this.countryId.equals(other.countryId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.countryId == null) ? 0 : this.countryId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Countries (");

        sb.append(countryId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
