/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Nuts implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer nutsId;
    private String name;
    private Integer countryId;

    public Nuts() {}

    public Nuts(Nuts value) {
        this.nutsId = value.nutsId;
        this.name = value.name;
        this.countryId = value.countryId;
    }

    public Nuts(
        Integer nutsId,
        String name,
        Integer countryId
    ) {
        this.nutsId = nutsId;
        this.name = name;
        this.countryId = countryId;
    }

    /**
     * Getter for <code>fab.nuts.nuts_id</code>.
     */
    public Integer getNutsId() {
        return this.nutsId;
    }

    /**
     * Setter for <code>fab.nuts.nuts_id</code>.
     */
    public void setNutsId(Integer nutsId) {
        this.nutsId = nutsId;
    }

    /**
     * Getter for <code>fab.nuts.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>fab.nuts.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>fab.nuts.country_id</code>.
     */
    public Integer getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>fab.nuts.country_id</code>.
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Nuts other = (Nuts) obj;
        if (this.nutsId == null) {
            if (other.nutsId != null)
                return false;
        }
        else if (!this.nutsId.equals(other.nutsId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.countryId == null) {
            if (other.countryId != null)
                return false;
        }
        else if (!this.countryId.equals(other.countryId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.nutsId == null) ? 0 : this.nutsId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.countryId == null) ? 0 : this.countryId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Nuts (");

        sb.append(nutsId);
        sb.append(", ").append(name);
        sb.append(", ").append(countryId);

        sb.append(")");
        return sb.toString();
    }
}
