/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import jhi.fab.codegen.enums.OutbreaksStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Outbreaks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer outbreakId;
    private String outbreakCode;
    private Integer userId;
    private String postcode;
    private String outcode;
    private String country;
    private String itlNuts;
    private Double realLatitude;
    private Double realLongitude;
    private Double viewLatitude;
    private Double viewLongitude;
    private LocalDate dateSubmitted;
    private LocalDate dateReceived;
    private Integer reportedVarietyId;
    private Integer severityId;
    private Integer sourceId;
    private String severityOther;
    private String sourceOther;
    private String userComments;
    private String adminComments;
    private OutbreaksStatus status;
    private Boolean isPublic;

    public Outbreaks() {}

    public Outbreaks(Outbreaks value) {
        this.outbreakId = value.outbreakId;
        this.outbreakCode = value.outbreakCode;
        this.userId = value.userId;
        this.postcode = value.postcode;
        this.outcode = value.outcode;
        this.country = value.country;
        this.itlNuts = value.itlNuts;
        this.realLatitude = value.realLatitude;
        this.realLongitude = value.realLongitude;
        this.viewLatitude = value.viewLatitude;
        this.viewLongitude = value.viewLongitude;
        this.dateSubmitted = value.dateSubmitted;
        this.dateReceived = value.dateReceived;
        this.reportedVarietyId = value.reportedVarietyId;
        this.severityId = value.severityId;
        this.sourceId = value.sourceId;
        this.severityOther = value.severityOther;
        this.sourceOther = value.sourceOther;
        this.userComments = value.userComments;
        this.adminComments = value.adminComments;
        this.status = value.status;
        this.isPublic = value.isPublic;
    }

    public Outbreaks(
        Integer outbreakId,
        String outbreakCode,
        Integer userId,
        String postcode,
        String outcode,
        String country,
        String itlNuts,
        Double realLatitude,
        Double realLongitude,
        Double viewLatitude,
        Double viewLongitude,
        LocalDate dateSubmitted,
        LocalDate dateReceived,
        Integer reportedVarietyId,
        Integer severityId,
        Integer sourceId,
        String severityOther,
        String sourceOther,
        String userComments,
        String adminComments,
        OutbreaksStatus status,
        Boolean isPublic
    ) {
        this.outbreakId = outbreakId;
        this.outbreakCode = outbreakCode;
        this.userId = userId;
        this.postcode = postcode;
        this.outcode = outcode;
        this.country = country;
        this.itlNuts = itlNuts;
        this.realLatitude = realLatitude;
        this.realLongitude = realLongitude;
        this.viewLatitude = viewLatitude;
        this.viewLongitude = viewLongitude;
        this.dateSubmitted = dateSubmitted;
        this.dateReceived = dateReceived;
        this.reportedVarietyId = reportedVarietyId;
        this.severityId = severityId;
        this.sourceId = sourceId;
        this.severityOther = severityOther;
        this.sourceOther = sourceOther;
        this.userComments = userComments;
        this.adminComments = adminComments;
        this.status = status;
        this.isPublic = isPublic;
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return this.outbreakId;
    }

    /**
     * Setter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer outbreakId) {
        this.outbreakId = outbreakId;
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public String getOutbreakCode() {
        return this.outbreakCode;
    }

    /**
     * Setter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public void setOutbreakCode(String outbreakCode) {
        this.outbreakCode = outbreakCode;
    }

    /**
     * Getter for <code>fab.outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fab.outbreaks.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fab.outbreaks.postcode</code>.
     */
    public String getPostcode() {
        return this.postcode;
    }

    /**
     * Setter for <code>fab.outbreaks.postcode</code>.
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * Getter for <code>fab.outbreaks.outcode</code>.
     */
    public String getOutcode() {
        return this.outcode;
    }

    /**
     * Setter for <code>fab.outbreaks.outcode</code>.
     */
    public void setOutcode(String outcode) {
        this.outcode = outcode;
    }

    /**
     * Getter for <code>fab.outbreaks.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>fab.outbreaks.country</code>.
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>fab.outbreaks.itl_nuts</code>.
     */
    public String getItlNuts() {
        return this.itlNuts;
    }

    /**
     * Setter for <code>fab.outbreaks.itl_nuts</code>.
     */
    public void setItlNuts(String itlNuts) {
        this.itlNuts = itlNuts;
    }

    /**
     * Getter for <code>fab.outbreaks.real_latitude</code>.
     */
    public Double getRealLatitude() {
        return this.realLatitude;
    }

    /**
     * Setter for <code>fab.outbreaks.real_latitude</code>.
     */
    public void setRealLatitude(Double realLatitude) {
        this.realLatitude = realLatitude;
    }

    /**
     * Getter for <code>fab.outbreaks.real_longitude</code>.
     */
    public Double getRealLongitude() {
        return this.realLongitude;
    }

    /**
     * Setter for <code>fab.outbreaks.real_longitude</code>.
     */
    public void setRealLongitude(Double realLongitude) {
        this.realLongitude = realLongitude;
    }

    /**
     * Getter for <code>fab.outbreaks.view_latitude</code>.
     */
    public Double getViewLatitude() {
        return this.viewLatitude;
    }

    /**
     * Setter for <code>fab.outbreaks.view_latitude</code>.
     */
    public void setViewLatitude(Double viewLatitude) {
        this.viewLatitude = viewLatitude;
    }

    /**
     * Getter for <code>fab.outbreaks.view_longitude</code>.
     */
    public Double getViewLongitude() {
        return this.viewLongitude;
    }

    /**
     * Setter for <code>fab.outbreaks.view_longitude</code>.
     */
    public void setViewLongitude(Double viewLongitude) {
        this.viewLongitude = viewLongitude;
    }

    /**
     * Getter for <code>fab.outbreaks.date_submitted</code>.
     */
    public LocalDate getDateSubmitted() {
        return this.dateSubmitted;
    }

    /**
     * Setter for <code>fab.outbreaks.date_submitted</code>.
     */
    public void setDateSubmitted(LocalDate dateSubmitted) {
        this.dateSubmitted = dateSubmitted;
    }

    /**
     * Getter for <code>fab.outbreaks.date_received</code>.
     */
    public LocalDate getDateReceived() {
        return this.dateReceived;
    }

    /**
     * Setter for <code>fab.outbreaks.date_received</code>.
     */
    public void setDateReceived(LocalDate dateReceived) {
        this.dateReceived = dateReceived;
    }

    /**
     * Getter for <code>fab.outbreaks.reported_variety_id</code>.
     */
    public Integer getReportedVarietyId() {
        return this.reportedVarietyId;
    }

    /**
     * Setter for <code>fab.outbreaks.reported_variety_id</code>.
     */
    public void setReportedVarietyId(Integer reportedVarietyId) {
        this.reportedVarietyId = reportedVarietyId;
    }

    /**
     * Getter for <code>fab.outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return this.severityId;
    }

    /**
     * Setter for <code>fab.outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer severityId) {
        this.severityId = severityId;
    }

    /**
     * Getter for <code>fab.outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>fab.outbreaks.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>fab.outbreaks.severity_other</code>.
     */
    public String getSeverityOther() {
        return this.severityOther;
    }

    /**
     * Setter for <code>fab.outbreaks.severity_other</code>.
     */
    public void setSeverityOther(String severityOther) {
        this.severityOther = severityOther;
    }

    /**
     * Getter for <code>fab.outbreaks.source_other</code>.
     */
    public String getSourceOther() {
        return this.sourceOther;
    }

    /**
     * Setter for <code>fab.outbreaks.source_other</code>.
     */
    public void setSourceOther(String sourceOther) {
        this.sourceOther = sourceOther;
    }

    /**
     * Getter for <code>fab.outbreaks.user_comments</code>.
     */
    public String getUserComments() {
        return this.userComments;
    }

    /**
     * Setter for <code>fab.outbreaks.user_comments</code>.
     */
    public void setUserComments(String userComments) {
        this.userComments = userComments;
    }

    /**
     * Getter for <code>fab.outbreaks.admin_comments</code>.
     */
    public String getAdminComments() {
        return this.adminComments;
    }

    /**
     * Setter for <code>fab.outbreaks.admin_comments</code>.
     */
    public void setAdminComments(String adminComments) {
        this.adminComments = adminComments;
    }

    /**
     * Getter for <code>fab.outbreaks.status</code>.
     */
    public OutbreaksStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fab.outbreaks.status</code>.
     */
    public void setStatus(OutbreaksStatus status) {
        this.status = status;
    }

    /**
     * Getter for <code>fab.outbreaks.is_public</code>.
     */
    public Boolean getIsPublic() {
        return this.isPublic;
    }

    /**
     * Setter for <code>fab.outbreaks.is_public</code>.
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Outbreaks other = (Outbreaks) obj;
        if (this.outbreakId == null) {
            if (other.outbreakId != null)
                return false;
        }
        else if (!this.outbreakId.equals(other.outbreakId))
            return false;
        if (this.outbreakCode == null) {
            if (other.outbreakCode != null)
                return false;
        }
        else if (!this.outbreakCode.equals(other.outbreakCode))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.postcode == null) {
            if (other.postcode != null)
                return false;
        }
        else if (!this.postcode.equals(other.postcode))
            return false;
        if (this.outcode == null) {
            if (other.outcode != null)
                return false;
        }
        else if (!this.outcode.equals(other.outcode))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.itlNuts == null) {
            if (other.itlNuts != null)
                return false;
        }
        else if (!this.itlNuts.equals(other.itlNuts))
            return false;
        if (this.realLatitude == null) {
            if (other.realLatitude != null)
                return false;
        }
        else if (!this.realLatitude.equals(other.realLatitude))
            return false;
        if (this.realLongitude == null) {
            if (other.realLongitude != null)
                return false;
        }
        else if (!this.realLongitude.equals(other.realLongitude))
            return false;
        if (this.viewLatitude == null) {
            if (other.viewLatitude != null)
                return false;
        }
        else if (!this.viewLatitude.equals(other.viewLatitude))
            return false;
        if (this.viewLongitude == null) {
            if (other.viewLongitude != null)
                return false;
        }
        else if (!this.viewLongitude.equals(other.viewLongitude))
            return false;
        if (this.dateSubmitted == null) {
            if (other.dateSubmitted != null)
                return false;
        }
        else if (!this.dateSubmitted.equals(other.dateSubmitted))
            return false;
        if (this.dateReceived == null) {
            if (other.dateReceived != null)
                return false;
        }
        else if (!this.dateReceived.equals(other.dateReceived))
            return false;
        if (this.reportedVarietyId == null) {
            if (other.reportedVarietyId != null)
                return false;
        }
        else if (!this.reportedVarietyId.equals(other.reportedVarietyId))
            return false;
        if (this.severityId == null) {
            if (other.severityId != null)
                return false;
        }
        else if (!this.severityId.equals(other.severityId))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.severityOther == null) {
            if (other.severityOther != null)
                return false;
        }
        else if (!this.severityOther.equals(other.severityOther))
            return false;
        if (this.sourceOther == null) {
            if (other.sourceOther != null)
                return false;
        }
        else if (!this.sourceOther.equals(other.sourceOther))
            return false;
        if (this.userComments == null) {
            if (other.userComments != null)
                return false;
        }
        else if (!this.userComments.equals(other.userComments))
            return false;
        if (this.adminComments == null) {
            if (other.adminComments != null)
                return false;
        }
        else if (!this.adminComments.equals(other.adminComments))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.isPublic == null) {
            if (other.isPublic != null)
                return false;
        }
        else if (!this.isPublic.equals(other.isPublic))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.outbreakId == null) ? 0 : this.outbreakId.hashCode());
        result = prime * result + ((this.outbreakCode == null) ? 0 : this.outbreakCode.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.postcode == null) ? 0 : this.postcode.hashCode());
        result = prime * result + ((this.outcode == null) ? 0 : this.outcode.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.itlNuts == null) ? 0 : this.itlNuts.hashCode());
        result = prime * result + ((this.realLatitude == null) ? 0 : this.realLatitude.hashCode());
        result = prime * result + ((this.realLongitude == null) ? 0 : this.realLongitude.hashCode());
        result = prime * result + ((this.viewLatitude == null) ? 0 : this.viewLatitude.hashCode());
        result = prime * result + ((this.viewLongitude == null) ? 0 : this.viewLongitude.hashCode());
        result = prime * result + ((this.dateSubmitted == null) ? 0 : this.dateSubmitted.hashCode());
        result = prime * result + ((this.dateReceived == null) ? 0 : this.dateReceived.hashCode());
        result = prime * result + ((this.reportedVarietyId == null) ? 0 : this.reportedVarietyId.hashCode());
        result = prime * result + ((this.severityId == null) ? 0 : this.severityId.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.severityOther == null) ? 0 : this.severityOther.hashCode());
        result = prime * result + ((this.sourceOther == null) ? 0 : this.sourceOther.hashCode());
        result = prime * result + ((this.userComments == null) ? 0 : this.userComments.hashCode());
        result = prime * result + ((this.adminComments == null) ? 0 : this.adminComments.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.isPublic == null) ? 0 : this.isPublic.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Outbreaks (");

        sb.append(outbreakId);
        sb.append(", ").append(outbreakCode);
        sb.append(", ").append(userId);
        sb.append(", ").append(postcode);
        sb.append(", ").append(outcode);
        sb.append(", ").append(country);
        sb.append(", ").append(itlNuts);
        sb.append(", ").append(realLatitude);
        sb.append(", ").append(realLongitude);
        sb.append(", ").append(viewLatitude);
        sb.append(", ").append(viewLongitude);
        sb.append(", ").append(dateSubmitted);
        sb.append(", ").append(dateReceived);
        sb.append(", ").append(reportedVarietyId);
        sb.append(", ").append(severityId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(severityOther);
        sb.append(", ").append(sourceOther);
        sb.append(", ").append(userComments);
        sb.append(", ").append(adminComments);
        sb.append(", ").append(status);
        sb.append(", ").append(isPublic);

        sb.append(")");
        return sb.toString();
    }
}
