/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import jhi.fab.codegen.enums.OutbreaksStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Outbreaks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer outbreakId;
    private String outbreakCode;
    private Integer userId;
    private Double reallatitude;
    private Double reallongitude;
    private Double viewlatitude;
    private Double viewlongitude;
    private LocalDate datesubmitted;
    private LocalDate datereceived;
    private Integer severityId;
    private Integer sourceId;
    private String severityother;
    private String sourceother;
    private String comments;
    private String additionalinfo;
    private OutbreaksStatus status;

    public Outbreaks() {}

    public Outbreaks(Outbreaks value) {
        this.outbreakId = value.outbreakId;
        this.outbreakCode = value.outbreakCode;
        this.userId = value.userId;
        this.reallatitude = value.reallatitude;
        this.reallongitude = value.reallongitude;
        this.viewlatitude = value.viewlatitude;
        this.viewlongitude = value.viewlongitude;
        this.datesubmitted = value.datesubmitted;
        this.datereceived = value.datereceived;
        this.severityId = value.severityId;
        this.sourceId = value.sourceId;
        this.severityother = value.severityother;
        this.sourceother = value.sourceother;
        this.comments = value.comments;
        this.additionalinfo = value.additionalinfo;
        this.status = value.status;
    }

    public Outbreaks(
        Integer outbreakId,
        String outbreakCode,
        Integer userId,
        Double reallatitude,
        Double reallongitude,
        Double viewlatitude,
        Double viewlongitude,
        LocalDate datesubmitted,
        LocalDate datereceived,
        Integer severityId,
        Integer sourceId,
        String severityother,
        String sourceother,
        String comments,
        String additionalinfo,
        OutbreaksStatus status
    ) {
        this.outbreakId = outbreakId;
        this.outbreakCode = outbreakCode;
        this.userId = userId;
        this.reallatitude = reallatitude;
        this.reallongitude = reallongitude;
        this.viewlatitude = viewlatitude;
        this.viewlongitude = viewlongitude;
        this.datesubmitted = datesubmitted;
        this.datereceived = datereceived;
        this.severityId = severityId;
        this.sourceId = sourceId;
        this.severityother = severityother;
        this.sourceother = sourceother;
        this.comments = comments;
        this.additionalinfo = additionalinfo;
        this.status = status;
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return this.outbreakId;
    }

    /**
     * Setter for <code>fab.outbreaks.outbreak_id</code>.
     */
    public void setOutbreakId(Integer outbreakId) {
        this.outbreakId = outbreakId;
    }

    /**
     * Getter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public String getOutbreakCode() {
        return this.outbreakCode;
    }

    /**
     * Setter for <code>fab.outbreaks.outbreak_code</code>.
     */
    public void setOutbreakCode(String outbreakCode) {
        this.outbreakCode = outbreakCode;
    }

    /**
     * Getter for <code>fab.outbreaks.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fab.outbreaks.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fab.outbreaks.realLatitude</code>.
     */
    public Double getReallatitude() {
        return this.reallatitude;
    }

    /**
     * Setter for <code>fab.outbreaks.realLatitude</code>.
     */
    public void setReallatitude(Double reallatitude) {
        this.reallatitude = reallatitude;
    }

    /**
     * Getter for <code>fab.outbreaks.realLongitude</code>.
     */
    public Double getReallongitude() {
        return this.reallongitude;
    }

    /**
     * Setter for <code>fab.outbreaks.realLongitude</code>.
     */
    public void setReallongitude(Double reallongitude) {
        this.reallongitude = reallongitude;
    }

    /**
     * Getter for <code>fab.outbreaks.viewLatitude</code>.
     */
    public Double getViewlatitude() {
        return this.viewlatitude;
    }

    /**
     * Setter for <code>fab.outbreaks.viewLatitude</code>.
     */
    public void setViewlatitude(Double viewlatitude) {
        this.viewlatitude = viewlatitude;
    }

    /**
     * Getter for <code>fab.outbreaks.viewLongitude</code>.
     */
    public Double getViewlongitude() {
        return this.viewlongitude;
    }

    /**
     * Setter for <code>fab.outbreaks.viewLongitude</code>.
     */
    public void setViewlongitude(Double viewlongitude) {
        this.viewlongitude = viewlongitude;
    }

    /**
     * Getter for <code>fab.outbreaks.dateSubmitted</code>.
     */
    public LocalDate getDatesubmitted() {
        return this.datesubmitted;
    }

    /**
     * Setter for <code>fab.outbreaks.dateSubmitted</code>.
     */
    public void setDatesubmitted(LocalDate datesubmitted) {
        this.datesubmitted = datesubmitted;
    }

    /**
     * Getter for <code>fab.outbreaks.dateReceived</code>.
     */
    public LocalDate getDatereceived() {
        return this.datereceived;
    }

    /**
     * Setter for <code>fab.outbreaks.dateReceived</code>.
     */
    public void setDatereceived(LocalDate datereceived) {
        this.datereceived = datereceived;
    }

    /**
     * Getter for <code>fab.outbreaks.severity_id</code>.
     */
    public Integer getSeverityId() {
        return this.severityId;
    }

    /**
     * Setter for <code>fab.outbreaks.severity_id</code>.
     */
    public void setSeverityId(Integer severityId) {
        this.severityId = severityId;
    }

    /**
     * Getter for <code>fab.outbreaks.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>fab.outbreaks.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>fab.outbreaks.severityOther</code>.
     */
    public String getSeverityother() {
        return this.severityother;
    }

    /**
     * Setter for <code>fab.outbreaks.severityOther</code>.
     */
    public void setSeverityother(String severityother) {
        this.severityother = severityother;
    }

    /**
     * Getter for <code>fab.outbreaks.sourceOther</code>.
     */
    public String getSourceother() {
        return this.sourceother;
    }

    /**
     * Setter for <code>fab.outbreaks.sourceOther</code>.
     */
    public void setSourceother(String sourceother) {
        this.sourceother = sourceother;
    }

    /**
     * Getter for <code>fab.outbreaks.comments</code>.
     */
    public String getComments() {
        return this.comments;
    }

    /**
     * Setter for <code>fab.outbreaks.comments</code>.
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * Getter for <code>fab.outbreaks.additionalInfo</code>.
     */
    public String getAdditionalinfo() {
        return this.additionalinfo;
    }

    /**
     * Setter for <code>fab.outbreaks.additionalInfo</code>.
     */
    public void setAdditionalinfo(String additionalinfo) {
        this.additionalinfo = additionalinfo;
    }

    /**
     * Getter for <code>fab.outbreaks.status</code>.
     */
    public OutbreaksStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>fab.outbreaks.status</code>.
     */
    public void setStatus(OutbreaksStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Outbreaks other = (Outbreaks) obj;
        if (this.outbreakId == null) {
            if (other.outbreakId != null)
                return false;
        }
        else if (!this.outbreakId.equals(other.outbreakId))
            return false;
        if (this.outbreakCode == null) {
            if (other.outbreakCode != null)
                return false;
        }
        else if (!this.outbreakCode.equals(other.outbreakCode))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.reallatitude == null) {
            if (other.reallatitude != null)
                return false;
        }
        else if (!this.reallatitude.equals(other.reallatitude))
            return false;
        if (this.reallongitude == null) {
            if (other.reallongitude != null)
                return false;
        }
        else if (!this.reallongitude.equals(other.reallongitude))
            return false;
        if (this.viewlatitude == null) {
            if (other.viewlatitude != null)
                return false;
        }
        else if (!this.viewlatitude.equals(other.viewlatitude))
            return false;
        if (this.viewlongitude == null) {
            if (other.viewlongitude != null)
                return false;
        }
        else if (!this.viewlongitude.equals(other.viewlongitude))
            return false;
        if (this.datesubmitted == null) {
            if (other.datesubmitted != null)
                return false;
        }
        else if (!this.datesubmitted.equals(other.datesubmitted))
            return false;
        if (this.datereceived == null) {
            if (other.datereceived != null)
                return false;
        }
        else if (!this.datereceived.equals(other.datereceived))
            return false;
        if (this.severityId == null) {
            if (other.severityId != null)
                return false;
        }
        else if (!this.severityId.equals(other.severityId))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.severityother == null) {
            if (other.severityother != null)
                return false;
        }
        else if (!this.severityother.equals(other.severityother))
            return false;
        if (this.sourceother == null) {
            if (other.sourceother != null)
                return false;
        }
        else if (!this.sourceother.equals(other.sourceother))
            return false;
        if (this.comments == null) {
            if (other.comments != null)
                return false;
        }
        else if (!this.comments.equals(other.comments))
            return false;
        if (this.additionalinfo == null) {
            if (other.additionalinfo != null)
                return false;
        }
        else if (!this.additionalinfo.equals(other.additionalinfo))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.outbreakId == null) ? 0 : this.outbreakId.hashCode());
        result = prime * result + ((this.outbreakCode == null) ? 0 : this.outbreakCode.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.reallatitude == null) ? 0 : this.reallatitude.hashCode());
        result = prime * result + ((this.reallongitude == null) ? 0 : this.reallongitude.hashCode());
        result = prime * result + ((this.viewlatitude == null) ? 0 : this.viewlatitude.hashCode());
        result = prime * result + ((this.viewlongitude == null) ? 0 : this.viewlongitude.hashCode());
        result = prime * result + ((this.datesubmitted == null) ? 0 : this.datesubmitted.hashCode());
        result = prime * result + ((this.datereceived == null) ? 0 : this.datereceived.hashCode());
        result = prime * result + ((this.severityId == null) ? 0 : this.severityId.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.severityother == null) ? 0 : this.severityother.hashCode());
        result = prime * result + ((this.sourceother == null) ? 0 : this.sourceother.hashCode());
        result = prime * result + ((this.comments == null) ? 0 : this.comments.hashCode());
        result = prime * result + ((this.additionalinfo == null) ? 0 : this.additionalinfo.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Outbreaks (");

        sb.append(outbreakId);
        sb.append(", ").append(outbreakCode);
        sb.append(", ").append(userId);
        sb.append(", ").append(reallatitude);
        sb.append(", ").append(reallongitude);
        sb.append(", ").append(viewlatitude);
        sb.append(", ").append(viewlongitude);
        sb.append(", ").append(datesubmitted);
        sb.append(", ").append(datereceived);
        sb.append(", ").append(severityId);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(severityother);
        sb.append(", ").append(sourceother);
        sb.append(", ").append(comments);
        sb.append(", ").append(additionalinfo);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
