/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Severities implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer severityId;
    private String severityName;

    public Severities() {}

    public Severities(Severities value) {
        this.severityId = value.severityId;
        this.severityName = value.severityName;
    }

    public Severities(
        Integer severityId,
        String severityName
    ) {
        this.severityId = severityId;
        this.severityName = severityName;
    }

    /**
     * Getter for <code>fab.severities.severity_id</code>.
     */
    public Integer getSeverityId() {
        return this.severityId;
    }

    /**
     * Setter for <code>fab.severities.severity_id</code>.
     */
    public void setSeverityId(Integer severityId) {
        this.severityId = severityId;
    }

    /**
     * Getter for <code>fab.severities.severity_name</code>.
     */
    public String getSeverityName() {
        return this.severityName;
    }

    /**
     * Setter for <code>fab.severities.severity_name</code>.
     */
    public void setSeverityName(String severityName) {
        this.severityName = severityName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Severities other = (Severities) obj;
        if (this.severityId == null) {
            if (other.severityId != null)
                return false;
        }
        else if (!this.severityId.equals(other.severityId))
            return false;
        if (this.severityName == null) {
            if (other.severityName != null)
                return false;
        }
        else if (!this.severityName.equals(other.severityName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.severityId == null) ? 0 : this.severityId.hashCode());
        result = prime * result + ((this.severityName == null) ? 0 : this.severityName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Severities (");

        sb.append(severityId);
        sb.append(", ").append(severityName);

        sb.append(")");
        return sb.toString();
    }
}
