/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sources implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer sourceId;
    private String sourceName;

    public Sources() {}

    public Sources(Sources value) {
        this.sourceId = value.sourceId;
        this.sourceName = value.sourceName;
    }

    public Sources(
        Integer sourceId,
        String sourceName
    ) {
        this.sourceId = sourceId;
        this.sourceName = sourceName;
    }

    /**
     * Getter for <code>fab.sources.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>fab.sources.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>fab.sources.source_name</code>.
     */
    public String getSourceName() {
        return this.sourceName;
    }

    /**
     * Setter for <code>fab.sources.source_name</code>.
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sources other = (Sources) obj;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        if (this.sourceName == null) {
            if (other.sourceName != null)
                return false;
        }
        else if (!this.sourceName.equals(other.sourceName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        result = prime * result + ((this.sourceName == null) ? 0 : this.sourceName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sources (");

        sb.append(sourceId);
        sb.append(", ").append(sourceName);

        sb.append(")");
        return sb.toString();
    }
}
