/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Subsamples implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer subsampleId;
    private Integer outbreakId;
    private Integer genotypeId;
    private LocalDate dategenotyped;
    private String comments;

    public Subsamples() {}

    public Subsamples(Subsamples value) {
        this.subsampleId = value.subsampleId;
        this.outbreakId = value.outbreakId;
        this.genotypeId = value.genotypeId;
        this.dategenotyped = value.dategenotyped;
        this.comments = value.comments;
    }

    public Subsamples(
        Integer subsampleId,
        Integer outbreakId,
        Integer genotypeId,
        LocalDate dategenotyped,
        String comments
    ) {
        this.subsampleId = subsampleId;
        this.outbreakId = outbreakId;
        this.genotypeId = genotypeId;
        this.dategenotyped = dategenotyped;
        this.comments = comments;
    }

    /**
     * Getter for <code>fab.subsamples.subsample_id</code>.
     */
    public Integer getSubsampleId() {
        return this.subsampleId;
    }

    /**
     * Setter for <code>fab.subsamples.subsample_id</code>.
     */
    public void setSubsampleId(Integer subsampleId) {
        this.subsampleId = subsampleId;
    }

    /**
     * Getter for <code>fab.subsamples.outbreak_id</code>.
     */
    public Integer getOutbreakId() {
        return this.outbreakId;
    }

    /**
     * Setter for <code>fab.subsamples.outbreak_id</code>.
     */
    public void setOutbreakId(Integer outbreakId) {
        this.outbreakId = outbreakId;
    }

    /**
     * Getter for <code>fab.subsamples.genotype_id</code>.
     */
    public Integer getGenotypeId() {
        return this.genotypeId;
    }

    /**
     * Setter for <code>fab.subsamples.genotype_id</code>.
     */
    public void setGenotypeId(Integer genotypeId) {
        this.genotypeId = genotypeId;
    }

    /**
     * Getter for <code>fab.subsamples.dateGenotyped</code>.
     */
    public LocalDate getDategenotyped() {
        return this.dategenotyped;
    }

    /**
     * Setter for <code>fab.subsamples.dateGenotyped</code>.
     */
    public void setDategenotyped(LocalDate dategenotyped) {
        this.dategenotyped = dategenotyped;
    }

    /**
     * Getter for <code>fab.subsamples.comments</code>.
     */
    public String getComments() {
        return this.comments;
    }

    /**
     * Setter for <code>fab.subsamples.comments</code>.
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Subsamples other = (Subsamples) obj;
        if (this.subsampleId == null) {
            if (other.subsampleId != null)
                return false;
        }
        else if (!this.subsampleId.equals(other.subsampleId))
            return false;
        if (this.outbreakId == null) {
            if (other.outbreakId != null)
                return false;
        }
        else if (!this.outbreakId.equals(other.outbreakId))
            return false;
        if (this.genotypeId == null) {
            if (other.genotypeId != null)
                return false;
        }
        else if (!this.genotypeId.equals(other.genotypeId))
            return false;
        if (this.dategenotyped == null) {
            if (other.dategenotyped != null)
                return false;
        }
        else if (!this.dategenotyped.equals(other.dategenotyped))
            return false;
        if (this.comments == null) {
            if (other.comments != null)
                return false;
        }
        else if (!this.comments.equals(other.comments))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.subsampleId == null) ? 0 : this.subsampleId.hashCode());
        result = prime * result + ((this.outbreakId == null) ? 0 : this.outbreakId.hashCode());
        result = prime * result + ((this.genotypeId == null) ? 0 : this.genotypeId.hashCode());
        result = prime * result + ((this.dategenotyped == null) ? 0 : this.dategenotyped.hashCode());
        result = prime * result + ((this.comments == null) ? 0 : this.comments.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subsamples (");

        sb.append(subsampleId);
        sb.append(", ").append(outbreakId);
        sb.append(", ").append(genotypeId);
        sb.append(", ").append(dategenotyped);
        sb.append(", ").append(comments);

        sb.append(")");
        return sb.toString();
    }
}
