/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String email;
    private Byte isAdmin;

    public Users() {}

    public Users(Users value) {
        this.userId = value.userId;
        this.email = value.email;
        this.isAdmin = value.isAdmin;
    }

    public Users(
        Integer userId,
        String email,
        Byte isAdmin
    ) {
        this.userId = userId;
        this.email = email;
        this.isAdmin = isAdmin;
    }

    /**
     * Getter for <code>fab.users.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fab.users.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fab.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>fab.users.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>fab.users.is_admin</code>.
     */
    public Byte getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * Setter for <code>fab.users.is_admin</code>.
     */
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.isAdmin == null) {
            if (other.isAdmin != null)
                return false;
        }
        else if (!this.isAdmin.equals(other.isAdmin))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.isAdmin == null) ? 0 : this.isAdmin.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(email);
        sb.append(", ").append(isAdmin);

        sb.append(")");
        return sb.toString();
    }
}
