/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserSessions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer userId;
    private String token;
    private LocalDateTime createdOn;

    public UserSessions() {}

    public UserSessions(UserSessions value) {
        this.userId = value.userId;
        this.token = value.token;
        this.createdOn = value.createdOn;
    }

    public UserSessions(
        Integer userId,
        String token,
        LocalDateTime createdOn
    ) {
        this.userId = userId;
        this.token = token;
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>fab.user_sessions.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>fab.user_sessions.user_id</code>.
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>fab.user_sessions.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>fab.user_sessions.token</code>.
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for <code>fab.user_sessions.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>fab.user_sessions.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserSessions other = (UserSessions) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!this.createdOn.equals(other.createdOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSessions (");

        sb.append(userId);
        sb.append(", ").append(token);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
