/*
 * This file is generated by jOOQ.
 */
package jhi.fab.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Varieties implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer varietyId;
    private String varietyName;

    public Varieties() {}

    public Varieties(Varieties value) {
        this.varietyId = value.varietyId;
        this.varietyName = value.varietyName;
    }

    public Varieties(
        Integer varietyId,
        String varietyName
    ) {
        this.varietyId = varietyId;
        this.varietyName = varietyName;
    }

    /**
     * Getter for <code>fab.varieties.variety_id</code>.
     */
    public Integer getVarietyId() {
        return this.varietyId;
    }

    /**
     * Setter for <code>fab.varieties.variety_id</code>.
     */
    public void setVarietyId(Integer varietyId) {
        this.varietyId = varietyId;
    }

    /**
     * Getter for <code>fab.varieties.variety_name</code>.
     */
    public String getVarietyName() {
        return this.varietyName;
    }

    /**
     * Setter for <code>fab.varieties.variety_name</code>.
     */
    public void setVarietyName(String varietyName) {
        this.varietyName = varietyName;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Varieties other = (Varieties) obj;
        if (this.varietyId == null) {
            if (other.varietyId != null)
                return false;
        }
        else if (!this.varietyId.equals(other.varietyId))
            return false;
        if (this.varietyName == null) {
            if (other.varietyName != null)
                return false;
        }
        else if (!this.varietyName.equals(other.varietyName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.varietyId == null) ? 0 : this.varietyId.hashCode());
        result = prime * result + ((this.varietyName == null) ? 0 : this.varietyName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Varieties (");

        sb.append(varietyId);
        sb.append(", ").append(varietyName);

        sb.append(")");
        return sb.toString();
    }
}
